enable = false

[[components]]

[components.Bars]
max_height = 0.75

[components.Bars.audio_conf]
amount_bars = 60
sensitivity = 0.20000000298023224
easing = "OutCubic"

[components.Bars.audio_conf.freq_range]
start = 50
end = 10000

[components.Bars.variant]
Color = [0, 255, 255, 255]
